<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>错误传播</title>
</head>
<script src="jquery-3.2.1.js"></script>
<body>
<script>
    $(function(){

        /*
        * 如果在一个函数内部发生了错误，它自身没有捕获，错误就会被抛到外层调用函数，
        * 如果外层函数也没有捕获，该错误会一直沿着函数调用链向上抛出，直到被JavaScript引擎捕获，代码终止执行。

         所以，我们不必在每一个函数内部捕获错误，只需要在合适的地方来个统一捕获，一网打尽：
        * */

        function main(s) {
            console.log('BEGIN main()');
            try {
                foo(s);
            } catch (e) {
                alert('出错了：' + e);
            }
            console.log('END main()');
        }

        function foo(s) {
            console.log('BEGIN foo()');
            bar(s);
            console.log('END foo()');
        }

        function bar(s) {
            console.log('BEGIN bar()');
            console.log('length = ' + s.length);
            console.log('END bar()');
        }

        main(null);


        /*
        * 当bar()函数传入参数null时，代码会报错，错误会向上抛给调用方foo()函数，
        * foo()函数没有try ... catch语句，所以错误继续向上抛给调用方main()函数，
        * main()函数有try ... catch语句，所以错误最终在main()函数被处理了。
        * */
    });
</script>
</body>
</html>